package analise.lexica;

public enum Token {
    PALAVRA,OPERADOR_ARITMETICO, OPERADOR_LOGICO,OP_ATRIBUICAO, OP_RELACIONAL, OP_BOOLEANO, SEPARADOR,
    ESPECIAL, COMENTARIO, ID, INT,NUMERO, ERROR, BRANCO, STRING     
}
