
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analise.sintatica;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int NUMERO = 33;
  public static final int MULTIPLICAR = 6;
  public static final int INTERROGACAO = 11;
  public static final int OPERADOR_ATRIBUICAO = 18;
  public static final int DIFERENTE = 15;
  public static final int OPERADOR_BOOLEANO = 19;
  public static final int TIPO_STRING = 29;
  public static final int INT = 28;
  public static final int FOR = 23;
  public static final int DOIS_PONTOS = 20;
  public static final int VIRGULA = 41;
  public static final int ABRECOLCHETES = 37;
  public static final int WRITE = 30;
  public static final int NEGACAO = 10;
  public static final int AND = 9;
  public static final int IGUAL = 14;
  public static final int OR = 8;
  public static final int BOOL = 27;
  public static final int MAIS = 2;
  public static final int ABRECHAVES = 39;
  public static final int FECHACHAVES = 40;
  public static final int FECHACOLCHETES = 38;
  public static final int UMENOS = 4;
  public static final int IF = 24;
  public static final int PONTOEVIRGULA = 42;
  public static final int ABREPARENTESES = 35;
  public static final int ID = 32;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int MAIOR = 12;
  public static final int error = 1;
  public static final int MENOS = 3;
  public static final int MENOR = 13;
  public static final int MOD = 7;
  public static final int BREAK = 21;
  public static final int ELSE = 22;
  public static final int DIVIDIR = 5;
  public static final int READ = 31;
  public static final int FECHAPARENTESES = 36;
  public static final int WHILE = 26;
  public static final int STRING = 34;
  public static final int MENOR_IGUAL = 17;
  public static final int MAIOR_IGUAL = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIS",
  "MENOS",
  "UMENOS",
  "DIVIDIR",
  "MULTIPLICAR",
  "MOD",
  "OR",
  "AND",
  "NEGACAO",
  "INTERROGACAO",
  "MAIOR",
  "MENOR",
  "IGUAL",
  "DIFERENTE",
  "MAIOR_IGUAL",
  "MENOR_IGUAL",
  "OPERADOR_ATRIBUICAO",
  "OPERADOR_BOOLEANO",
  "DOIS_PONTOS",
  "BREAK",
  "ELSE",
  "FOR",
  "IF",
  "RETURN",
  "WHILE",
  "BOOL",
  "INT",
  "TIPO_STRING",
  "WRITE",
  "READ",
  "ID",
  "NUMERO",
  "STRING",
  "ABREPARENTESES",
  "FECHAPARENTESES",
  "ABRECOLCHETES",
  "FECHACOLCHETES",
  "ABRECHAVES",
  "FECHACHAVES",
  "VIRGULA",
  "PONTOEVIRGULA"
  };
}

